#!/usr/bin/python

import sys

if len(sys.argv) < 3:
    print "Usage:"
    print "\ttrigrams prefix maxlen"
    print "\t\t- or -"
    print "\ttrigrams suffix -maxlen"
    sys.exit(1)

prefix = sys.argv[1].upper()

if len(prefix) < 2:
    print "Use prefix/suffix with at least 2 characters"
    sys.exit(2)

maxlen = int(sys.argv[2])
rev = False
if maxlen < 0:
    maxlen = -maxlen
    rev = True

t = {}
u = {}

with open('trigrams.txt') as f:
    for l in f.readlines():
        if l.startswith(';'):
            continue
        k,v = l[0]+l[1], l[2]
        if not k in t:
            t[k] = []
        t[k].append(v)
        k,v = l[1]+l[2], l[0]
        if not k in u:
            u[k] = []
        u[k].append(v)

def tree(p,):
    if p[-2:] not in t or len(p) >= maxlen:
        print p
        return
    for s in t[p[-2:]]:
        if s == '#':
            print p
        else:
            tree(p+s)

def tree_rev(p):
    if p[:2] not in u or len(p) >= maxlen:
        print p
        return
    for s in u[p[:2]]:
        if s == '#':
            print p
        else:
            tree_rev(s+p)

if not rev:
    tree(prefix)
else:
    tree_rev(prefix)
